### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by centi** [alg/nativescript-fcm#5]
I have troubles installing your plugin. I followed the instructions in readme (Are those complete? What about the permissions in Android manifest?). Then I tried to install the plugin using `tsc plugin add nativescript-fcm` which ended in 404 error. So I installed it using the GIT url.

But after I include the plugin in my javascript code, I get this error:

```
JS:     at Object.<anonymous> (/data/data/org.nativescript.bikefense/files/app/tns_modules/nativescript-fcm/index.js:3:32)
```

Am I missing some dependency?

**Comment by alg** [comment]
Nope. I just created a new app and installed the plugin from Github, created the app in Firebase, got my json file and followed the instructions in README. In the app itself I just added the following to `app.js`:

```
var FCM = require("nativescript-fcm");
console.log(FCM.getToken());
```

On first run it returns `null` (not sure why, but I guess it'll call onTokenRefresh), on the second I got token.

**Comment by centi** [comment]
I wonder what these two missing packages are:

```
var Plugin      = com.noizeramp.nsfcm.Plugin;
var Listener    = com.noizeramp.nsfcm.Listener;
```

What version of NativeScript do you use? I'm using NS2 with Angular.

**Comment by alg** [comment]
They are not missing. They are in native code (classes.jar). Using version 2.0.1.

**Comment by centi** [comment]
Sorry, now I realized, that in my first comment I didn't post the right error message. It is:

```
JS: TypeError: Cannot read property 'nsfcm' of undefined
JS:     at Object.<anonymous> (/data/data/org.nativescript.bikefense/files/app/tns_modules/nativescript-fcm/index.js:3:32)
```

That **'nsfcm' of undefined** gave me the idea, that I'm missing the `noizeramp` package. Thanks for pointing me to the classes.jar, I will look around.

**Comment by alg** [comment]
Interesting. Please check that you have it in the `node_modules/nativescript-fcm/platforms/android/libs` folder.

**Comment by centi** [comment]
So, I had to completely remove the /platforms/android folder and then add it back again `tns platform add android`.

Now it seems to be working fine. Sorry for the false alarm and thanks for the plugin :)
